version: '3.9'
services:
  web:
    build:
      context: ./app
      tags:
        - hardware_store:2
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - "8080:8000"
    env_file:
      - ./.env
    depends_on:
      - mongodb
      - postgres
  mongodb:
      image: mongo
      env_file:
        - ./.env
      volumes:
        - mongodb_data:/data/db
  postgres:
      image: postgres
      env_file:
        - ./.env
      volumes:
        - postgres_data:/var/lib/postgresql/data

volumes:
  mongodb_data:
  postgres_data: